services:
  database:
    container_name: library-api
    image: "postgres:16.0-alpine3.18"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "library-db"
      POSTGRES_HOST: "localhost"
      POSTGRES_PORT: 5432
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
